spring:
  application:
    name: shop-demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev_shop?serverTimezone=UTC
    username:
    password:
  mail:
    protocol: smtp
    host: outlook.office365.com
    port: 587
    username: no-reply@prprv.com
    password: Cay88761@prprv
    default-encoding: UTF-8
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: outlook.office365.com

server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /

springdoc:
  packages-to-scan: com.prprv.shop.controller
  swagger-ui:
    enabled: true
    path: /doc

mybatis:
  # 配置mapper接口路径
  mapper-locations: classpath:/mapper/*.xml
  # 配置类型别名包路径
  type-aliases-package: com.prprv.shop.model.entity
  # 下划线映射为驼峰
  configuration.map-underscore-to-camel-case: true
  # 禁用缓存
  configuration.cache-enabled: false

